-- =====================================================================
-- TaskFlow database schema (SQLite)
--
-- Relationship:
--   Board ──< Columns ──< Tasks
--
-- Decisions:
--   * Every table has an INTEGER PRIMARY KEY (rowid alias).
--   * columns.board_id references boards.id with ON DELETE CASCADE:
--       deleting a board removes its columns.
--   * tasks.column_id references columns.id with ON DELETE CASCADE:
--       deleting a column removes its tasks.
--   * A task's status is derived from the column it belongs to; it is
--       NOT stored redundantly on the task row.
--   * tasks.priority is restricted by a CHECK constraint.
--   * Timestamps are ISO-8601 / SQLite-compatible (UTC), generated by
--       the database at insert time so the backend and tests agree.
-- =====================================================================

PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS boards (
    id         INTEGER PRIMARY KEY AUTOINCREMENT,
    title      TEXT    NOT NULL,
    created_at TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

CREATE TABLE IF NOT EXISTS columns (
    id         INTEGER PRIMARY KEY AUTOINCREMENT,
    board_id   INTEGER NOT NULL,
    title      TEXT    NOT NULL,
    position   INTEGER NOT NULL DEFAULT 0,
    created_at TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    FOREIGN KEY (board_id) REFERENCES boards (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS tasks (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    column_id   INTEGER NOT NULL,
    title       TEXT    NOT NULL,
    description TEXT,
    priority    TEXT    NOT NULL DEFAULT 'MEDIUM'
        CHECK (priority IN ('LOW', 'MEDIUM', 'HIGH')),
    created_at  TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    FOREIGN KEY (column_id) REFERENCES columns (id) ON DELETE CASCADE
);

-- Indexes used by the required queries.
CREATE INDEX IF NOT EXISTS idx_columns_board ON columns (board_id);
CREATE INDEX IF NOT EXISTS idx_tasks_column  ON tasks (column_id);
CREATE INDEX IF NOT EXISTS idx_tasks_priority_created
    ON tasks (priority, created_at DESC);
