-- =====================================================================
-- TaskFlow database schema (MySQL 8)
--
-- Relationship:
--   Board ──< Columns ──< Tasks
--
-- Decisions:
--   * InnoDB for real foreign-key enforcement with ON DELETE CASCADE.
--   * AUTO_INCREMENT surrogate keys mirroring the previous rowid aliases.
--   * A task's status is derived from the column it belongs to; it is
--     NOT stored redundantly on the task row.
--   * tasks.priority is restricted by a CHECK constraint.
--   * Timestamps are UTC, generated by the database at insert time so the
--     backend and tests agree.
-- =====================================================================

CREATE TABLE IF NOT EXISTS boards (
    id         INT UNSIGNED NOT NULL AUTO_INCREMENT,
    title      VARCHAR(255) NOT NULL,
    created_at DATETIME(3)  NOT NULL DEFAULT (UTC_TIMESTAMP(3)),
    PRIMARY KEY (id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS columns (
    id         INT UNSIGNED NOT NULL AUTO_INCREMENT,
    board_id   INT UNSIGNED NOT NULL,
    title      VARCHAR(255) NOT NULL,
    position   INT          NOT NULL DEFAULT 0,
    created_at DATETIME(3)  NOT NULL DEFAULT (UTC_TIMESTAMP(3)),
    PRIMARY KEY (id),
    KEY idx_columns_board (board_id),
    CONSTRAINT fk_columns_board
        FOREIGN KEY (board_id) REFERENCES boards (id) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS tasks (
    id          INT UNSIGNED NOT NULL AUTO_INCREMENT,
    column_id   INT UNSIGNED NOT NULL,
    title       VARCHAR(255) NOT NULL,
    description TEXT,
    priority    VARCHAR(10)  NOT NULL DEFAULT 'MEDIUM',
    created_at  DATETIME(3)  NOT NULL DEFAULT (UTC_TIMESTAMP(3)),
    PRIMARY KEY (id),
    KEY idx_tasks_column (column_id),
    KEY idx_tasks_priority_created (priority, created_at DESC),
    CONSTRAINT fk_tasks_column
        FOREIGN KEY (column_id) REFERENCES columns (id) ON DELETE CASCADE,
    CONSTRAINT chk_tasks_priority
        CHECK (priority IN ('LOW', 'MEDIUM', 'HIGH'))
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;